#!/bin/sh

# Copyright (c) 2011 Colivre
# Author Joenio Costa <joenio AT perl.org.br>
#
# Add to snmpd.conf for example:
#
# exec delayed_job $PATH/check_proc delayed_job
#
# This is usefull to check process name of scripts (Perl, Ruby, etc) via SNMP
# because SNMP proc cant see that. SNMP proc uses "ps -e" and scripts Perl for
# example appear as perl instead of name of script.
#
# License: GPLv2+

PROCNAME=$1
USERNAME=$2

ok() {
   echo "OK $PROCNAME process is running"
   exit 0
}
crit() {
   echo "CRITICAL $PROCNAME process isnt running"
   exit 2
}

if [ -z $PROCNAME ]; then
   echo "Please inform proc name in command line."
   echo "   eg.: check_proc apache2"
   echo "You can restrict by user"
   echo "   eg.: check_proc apache www-data"
   exit 3
fi

PROC=`echo $PROCNAME | sed 's/^\(.\)/[\1]/'`

if [ -z $USERNAME ]; then
   (ps -A -o comm,args | grep -v $0 | grep $PROC > /dev/null) && ok || crit
else
   (ps -u $USERNAME -o comm,args | grep -v $0 | grep $PROC > /dev/null) && ok || crit
fi
