#!/bin/sh

# Copyright (c) 2015 Colivre
# Author Joenio Costa <joenio AT colivre.coop.br>
#
# Check kernel linux route table via `ip route show` command.
#
# On Debian add to /etc/snmpd.conf file:
#
#   { exec OR extend } <IP TO CHECK> $PATH/check_route <IP TO CHECK>
#
# Example:
#
#   extend 10.2.1.1 $PATH/check_route 10.2.1.1
#
# License: GPLv2+

ROUTE=$1

ok() {
   echo "OK $ROUTE route exists"
   exit 0
}
crit() {
   echo "CRITICAL $ROUTE route doesn't exists"
   exit 2
}

if [ -z $ROUTE ]; then
   echo "Please inform IP in command line."
   echo "   eg.: check_route 10.2.1.1"
   exit 3
fi

if [ `ip route show $ROUTE | wc -l` -eq 0 ]; then
   crit
else
   ok
fi
